SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `users` (`id` INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (`id`)) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_czech_ci;

ALTER TABLE `users` MODIFY COLUMN `login` VARCHAR(225) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `password` VARCHAR(100) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `last_login` INT(20) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `created` INT(20) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `firstname` VARCHAR(225) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `lastname` VARCHAR(225) NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `email` VARCHAR(225) NOT NULL;
